// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

import (
	"github.com/forrana/gramma-trainer/api/data"
)

type NewExercise struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type NewSection struct {
	Name          string   `json:"name"`
	Description   string   `json:"description"`
	NextSection   string   `json:"nextSection"`
	PrevSection   string   `json:"prevSection"`
	ChildSections []string `json:"childSections"`
	Exercises     []string `json:"exercises"`
	Tags          []string `json:"tags"`
}

type NewTag struct {
	Name string `json:"name"`
}

type NewTrial struct {
	Exercise string `json:"exercise"`
	Section  string `json:"section"`
}

type Section struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Description   *string         `json:"description"`
	NextSection   *Section        `json:"nextSection"`
	PrevSection   *Section        `json:"prevSection"`
	ChildSections []Section       `json:"childSections"`
	Exercises     []data.Exercise `json:"exercises"`
	Tags          []Tag           `json:"tags"`
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Trial struct {
	ID       string        `json:"id"`
	Exercise data.Exercise `json:"exercise"`
	Section  Section       `json:"section"`
	Date     int           `json:"date"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
